### ISSUE TITLE
By 'cp /etc/resolv.conf /etc' did you mean 'cp /etc/resolv.conf /path/to/MrChrootBSD/chroot/etc'?

### ISSUE THREAD

**Issue by AKA-Cigma** [nrootconauto/MrChrootBSD#3]
Also I assume `./mrhcroot chroot /bin/sh` to be `./mrchroot chroot /bin/sh`.
Maybe the README could be a little more readable, for example, add `git clone https://github.com/nrootconauto/MrChrootBSD.git`  `cd MrChrootBSD` before `wget https://download.freebsd.org/releases/amd64/14.1-RELEASE/base.txz`.
Hope these small suggestions would help.

**Comment by ghost** [comment]
Thanks. Sorry for the slow response. Im debugging away recently on the project. I am serious about it. I didnt know anyone was using this. I put a notice on "Do not use this,unstable" on it too. I except someone usable within next week. 

  I also corrected the mrhchoot typo.
